### ISSUE TITLE
bug: mobile phone number is empty on Android 12

### ISSUE THREAD

**Issue by shivamHylo** [jonz94/capacitor-sim#3]
i have installed this plugin but i am not getting mobile number in the result.

**Comment by jonz94** [comment]
Hi @shivamHylo,

Which OS are you testing the plugin on?
Currently, the plugin can only retrieve mobile numbers on Android devices running version 12 or lower.

For Android 13, some changes will be needed to the implementation to retrieve mobile numbers.
I plan to address this after Capacitor officially adds support for Android 13 with the release of Capacitor 5.

Regarding iOS, Apple does not allow developers to retrieve mobile numbers. You can find more information about this policy in the Apple Developer Forums (Reference: https://developer.apple.com/forums/thread/9171).
Therefore, if you are not able to retrieve mobile numbers on iOS devices, this is expected behavior.

**Comment by tarangshah19** [comment]
when you update for For Android 13,

**Comment by harshallcode** [comment]
Now that the capacitor 5 beta has been released, will you start working on Android 13 support?

**Comment by jonz94** [comment]
Hi @tarangshah19 @harshall666

I've created a separate issue specifically for Capacitor 5 and Android 13 support (https://github.com/jonz94/capacitor-sim/issues/4).

I'd like to suggest that we continue this discussion on there. Thank you!

**Comment by jonz94** [comment]
Hi @shivamHylo, sorry for pinging you again.

Is your end result different from the following?

> Currently, the plugin can only retrieve mobile numbers on Android devices running version 12 or lower.
>
> For Android 13, some changes will be needed to the implementation to retrieve mobile numbers.
>
> Regarding iOS, Apple does not allow developers to retrieve mobile numbers. You can find more information about this policy in the Apple Developer Forums (Reference: https://developer.apple.com/forums/thread/9171).
Therefore, if you are not able to retrieve mobile numbers on iOS devices, this is expected behavior.

I would appreciate it if you could provide me with more details, so that I can take a deeper look and address the issue.

**Comment by shivamHylo** [comment]
I have found the issue in android 12, in lower android version it's working fine

Regards,
Shivam Thakur
Developer
m: +91 9012999342 | e: ***@***.***
Hylobiz | India • UAE • USA • Indonesia
[Facebook icon]<https://www.facebook.com/gohyloapp/> [LinkedIn icon] <https://www.linkedin.com/company/smeneobank/>  [Twitter icon] <https://twitter.com/HyLoBiz/>  [Youtbue icon] <https://www.youtube.com/channel/UCHoDm2D46WhKUqNfeIo91Jg>  [Instagram icon] <https://www.instagram.com/hylobiz/>  [Medium icon] ***@***.***>

________________________________

**Comment by harshallcode** [comment]
For me, the plugin is working as expected till Android 12. In Android 13, the number property returns an empty string (""). Other properties(carrier name, etc) are returning data as expected.

Regards,
Harshal Patil

**Update:- I haven't tested this plugin on Android 12 yet. I wrongfully assumed it should've worked on 12. It works fine till 11**

**Comment by jonz94** [comment]
Hi there,

I just publish a new version.
Upgrade the plugin to `@jonz94/capacitor-sim@1.0.5` should be able to fix this issue.
