### ISSUE TITLE
Android phones lower than 13 can't fetch phone numbers if not already set in settings.

### ISSUE THREAD

**Issue by harshallcode** [jonz94/capacitor-sim#7]
If the mobile number is not set in the sim card settings, the number returns an empty string. However, android 13 fetches the user's phone number properly even if the number is not set in settings.

**Comment by jonz94** [comment]
Sorry for the late reply...

In some circumstances, the phone number will return an empty string, so I think this might be the excepted behavior.

For your situation, the reason why it works on Android 13 but not on Android <= 12 might be the fact that Android 13 has a newer API, which behaves differently from the API for Android <= 12.

<details>
<summary>The very detailed explanation: Why are the behaviors different on Android <= 12 and Android >= 13</summary>

- For Android >= 13, the plugin uses the [android.telephony.SubscriptionManager getPhoneNumber(subscriptionId) method](https://developer.android.com/reference/android/telephony/SubscriptionManager#getPhoneNumber(int)) under the hood to get the phone number of the device:<br>
![image](https://github.com/jonz94/capacitor-sim/assets/16042676/9c571c6c-4415-4f72-a87d-9b692312f47a)

- For Android <= 12, the plugin uses the [android.telephony.SubscriptionInfo getNumber() method](https://developer.android.com/reference/android/telephony/SubscriptionInfo#getNumber()) instead:<br>
![image](https://user-images.githubusercontent.com/16042676/232310958-84e00d52-981b-4a3a-8067-62b75291549c.png)

- In both cases, if the requirement is not met, it is possible that it will return the phone number as an empty string.

</details>

For now, I'm not 100% sure if this issue is a bug or not. I will conduct further investigation and provide more information here.

**Comment by harshallcode** [comment]
Thanks for the response. I also believe the new API and permissions in Android 13 must've given it access to phone numbers not found inside the setting itself.
